name: Build artifacts
on:
    push:
        branches:
            - master
            - dev-pkg

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm install
            - run: npm run build
            - uses: actions/upload-artifact@v2
              with:
                  name: jsprismarine-x64-linux
                  path: dist/jsprismarine-linux
            - uses: actions/upload-artifact@v2
              with:
                  name: jsprismarine-x64-macos
                  path: dist/jsprismarine-macos
            - uses: actions/upload-artifact@v2
              with:
                  name: jsprismarine-x64-win.exe
                  path: dist/jsprismarine-win.exe
