name: Executable
on:
    push:

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
    nightly:
        name: 🚚 Build nightly executable
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: 📦 Install
              uses: ./.github/common/install

            - name: 🔨 Build
              run: pnpm run build

            - name: 🔨 Build Executable
              run: pnpm run package

            - name: 🚚 Publish Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: prismarine-${{ matrix.os }}
                  path: ./dist/prismarine

